services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tyuiu_ratings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8777:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tyuiu_ratings"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tyuiu_ratings
    restart: unless-stopped


volumes:
  postgres_data: