services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tyuiu_ratings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8532:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 3


volumes:
  postgres_data: