[tool.ruff]
# Включаем основные правила линтинга (аналог flake8 + isort + pyupgrade)
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort (сортировка импортов)
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade (модернизация кода)
  "PL",  # pylint (часть правил)
  "RUF", # встроенные правила Ruff
  "ERA", # обнаружение закомментированного кода
  "PD",  # pandas-стиль
]

# Игнорируемые правила
ignore = [
  "E501",  # Длина строки (можно настроить отдельно)
  "PLR2004", # Magic value (если используете константы)
  "PD011"  # `.values` в pandas (иногда нужно)
]

# Максимальная длина строки
line-length = 120

# Автофикс (--fix)
fixable = ["ALL"]
unfixable = []

# Настройка isort (сортировка импортов)
[tool.ruff.isort]
known-first-party = ["src"]  # если у вас модуль лежит в src/
required-imports = ["from __future__ import annotations"]
lines-after-imports = 2

# Настройка flake8-bugbear
[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["typing.FrozenSet"]

# Настройка pyupgrade (модернизация кода)
[tool.ruff.pyupgrade]
keep-runtime-typing = true