"""Initial revision

Revision ID: 83e6b3f0df19
Revises: 
Create Date: 2025-06-13 17:08:19.944387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e6b3f0df19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female')", name='check_all_genders'),
    sa.CheckConstraint('gpa >= 3 AND gpa <= 5', name='check_gpa_range'),
    sa.PrimaryKeyConstraint('applicant_id', 'id'),
    sa.UniqueConstraint('applicant_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('id_index', 'profiles', ['user_id', 'applicant_id'], unique=False)
    op.create_table('applicant',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('bonus_points', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bonus_points >= 0 AND bonus_points <= 10', name='check_bonus_points_range'),
    sa.CheckConstraint('points >= 0 AND points <= 310', name='check_points_range'),
    sa.ForeignKeyConstraint(['applicant_id'], ['profiles.applicant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('direction_index', 'applicant', ['direction'], unique=False)
    op.create_table('exams',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points <= 100 AND points >= 0', name='check_exam_points_range'),
    sa.ForeignKeyConstraint(['applicant_id'], ['profiles.applicant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['profiles.applicant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('exams')
    op.drop_index('direction_index', table_name='applicant')
    op.drop_table('applicant')
    op.drop_index('id_index', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
